"""initial schema

Revision ID: 1871c05ee2a2
Revises: 
Create Date: 2026-09-17 16:02:32.630862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1871c05ee2a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        # server_default is deliberate. This column is NOT NULL and the table
        # already holds rows, so without it MySQL backfills them from the type's
        # implicit default - a silent 0.00 on a money column. Stating it makes
        # the backfill value an explicit decision that is recorded in the
        # migration rather than inferred from server configuration.
        batch_op.add_column(sa.Column(
            'balance',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default='0.00',
        ))

    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_opening_balance', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('source_closing_balance', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('destination_opening_balance', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('destination_closing_balance', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_column('destination_closing_balance')
        batch_op.drop_column('destination_opening_balance')
        batch_op.drop_column('source_closing_balance')
        batch_op.drop_column('source_opening_balance')

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
