"""Record the instrument that settled a transfer

Revision ID: 2906745bd5b0
Revises: 2d0f3ca37e25
Create Date: 2026-09-21 14:23:50.195106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2906745bd5b0'
down_revision = '2d0f3ca37e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_instrument', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('source_vpa', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_column('source_vpa')
        batch_op.drop_column('source_instrument')

    # ### end Alembic commands ###
