"""Razorpay UPI fields on emi_payments

Revision ID: 2d0f3ca37e25
Revises: 1871c05ee2a2
Create Date: 2026-09-21 13:20:49.060781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0f3ca37e25'
down_revision = '1871c05ee2a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emi_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_signature', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('upi_app', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('upi_vpa', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('upi_rrn', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_emi_payments_gateway_payment_id'), ['gateway_payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_emi_payments_upi_rrn'), ['upi_rrn'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emi_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emi_payments_upi_rrn'))
        batch_op.drop_index(batch_op.f('ix_emi_payments_gateway_payment_id'))
        batch_op.drop_column('upi_rrn')
        batch_op.drop_column('upi_vpa')
        batch_op.drop_column('upi_app')
        batch_op.drop_column('gateway_signature')

    # ### end Alembic commands ###
