"""add missing columns

Revision ID: 3eaa1c6847bf
Revises: a3d7e5c2b918
Create Date: 2026-10-09 11:56:03.766467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3eaa1c6847bf'
down_revision = 'a3d7e5c2b918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bureau_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bureau_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bureau_error', sa.String(length=255), nullable=True))
        batch_op.drop_column('eligibility_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eligibility_score', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.drop_column('bureau_error')
        batch_op.drop_column('bureau_code')
        batch_op.drop_column('bureau_provider')

    # ### end Alembic commands ###
