"""Record test card scenario

Revision ID: 9abf36599b0d
Revises: 2906745bd5b0
Create Date: 2026-09-22 12:09:40.935247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abf36599b0d'
down_revision = '2906745bd5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_scenario', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('test_scenario')

    # ### end Alembic commands ###
