"""Credit line: applications, accounts, statements, transactions

Written by hand rather than autogenerated. app.py calls db.create_all() at boot,
so by the time `flask db migrate` ran the tables already existed and alembic
correctly reported no diff. Without this file a deployment that builds its
schema from migrations alone - which is the only safe way to build one, since
create_all never alters an existing table - would not have these tables at all.

Each create is guarded on the table's absence for the same reason: on a
development database create_all has already made them, and an unguarded CREATE
TABLE would fail on the first run.

Revision ID: b2e6d91c4a7f
Revises: a1f4c7b9de02
Create Date: 2026-09-24
"""
import sqlalchemy as sa
from alembic import op

revision = 'b2e6d91c4a7f'
down_revision = 'a1f4c7b9de02'
branch_labels = None
depends_on = None


def _existing():
    return set(sa.inspect(op.get_bind()).get_table_names())


def upgrade():
    tables = _existing()

    if 'credit_applications' not in tables:
        op.create_table(
            'credit_applications',
            sa.Column('application_id', sa.CHAR(36), primary_key=True),
            sa.Column('user_id', sa.CHAR(36),
                      sa.ForeignKey('users.user_id'), nullable=False),
            sa.Column('status', sa.String(20), nullable=False),

            sa.Column('employment_type', sa.String(20), nullable=False),
            sa.Column('monthly_income', sa.Numeric(12, 2), nullable=False),
            sa.Column('existing_emi_outflow', sa.Numeric(12, 2), nullable=False,
                      server_default='0'),
            sa.Column('requested_limit', sa.Numeric(12, 2), nullable=True),

            sa.Column('approved_limit', sa.Numeric(12, 2), nullable=True),
            sa.Column('offered_limit', sa.Numeric(12, 2), nullable=True),
            sa.Column('eligibility_score', sa.Numeric(5, 2), nullable=True),
            sa.Column('decision_reason', sa.String(50), nullable=True),
            sa.Column('decision_note', sa.String(500), nullable=True),

            sa.Column('kyc_verified_at', sa.DateTime(), nullable=True),
            sa.Column('submitted_at', sa.DateTime(), nullable=True),
            sa.Column('decided_at', sa.DateTime(), nullable=True),
            sa.Column('decided_by', sa.String(36), nullable=True),

            sa.Column('created_on', sa.DateTime(), nullable=False),
            sa.Column('updated_on', sa.DateTime(), nullable=False),
        )
        op.create_index('ix_credit_applications_user_id',
                        'credit_applications', ['user_id'])
        op.create_index('ix_credit_applications_status',
                        'credit_applications', ['status'])
        op.create_index('ix_credit_app_user_status',
                        'credit_applications', ['user_id', 'status'])

    if 'credit_accounts' not in tables:
        op.create_table(
            'credit_accounts',
            sa.Column('credit_account_id', sa.CHAR(36), primary_key=True),
            sa.Column('user_id', sa.CHAR(36),
                      sa.ForeignKey('users.user_id'), nullable=False),
            sa.Column('application_id', sa.CHAR(36),
                      sa.ForeignKey('credit_applications.application_id'),
                      nullable=False),
            sa.Column('status', sa.String(20), nullable=False),

            # No PAN column, by design. Only what is shown, plus the BIN.
            sa.Column('card_bin', sa.String(6), nullable=False),
            sa.Column('card_last4', sa.String(4), nullable=False),
            sa.Column('card_network', sa.String(20), nullable=False),
            sa.Column('name_on_card', sa.String(80), nullable=False),
            sa.Column('expiry_month', sa.String(2), nullable=False),
            sa.Column('expiry_year', sa.String(4), nullable=False),

            sa.Column('credit_limit', sa.Numeric(12, 2), nullable=False),
            sa.Column('available_credit', sa.Numeric(12, 2), nullable=False),
            sa.Column('current_outstanding', sa.Numeric(12, 2), nullable=False,
                      server_default='0'),
            sa.Column('currency', sa.String(3), nullable=False,
                      server_default='INR'),

            sa.Column('purpose', sa.String(20), nullable=True),
            sa.Column('purpose_note', sa.String(200), nullable=True),
            sa.Column('purpose_declared_at', sa.DateTime(), nullable=True),

            sa.Column('statement_day', sa.Integer(), nullable=False),
            sa.Column('grace_days', sa.Integer(), nullable=False),

            sa.Column('activated_at', sa.DateTime(), nullable=True),
            sa.Column('blocked_at', sa.DateTime(), nullable=True),
            sa.Column('block_reason', sa.String(200), nullable=True),
            sa.Column('closed_at', sa.DateTime(), nullable=True),

            sa.Column('created_on', sa.DateTime(), nullable=False),
            sa.Column('updated_on', sa.DateTime(), nullable=False),
        )
        op.create_index('ix_credit_accounts_user_id',
                        'credit_accounts', ['user_id'])
        op.create_index('ix_credit_accounts_application_id',
                        'credit_accounts', ['application_id'])
        op.create_index('ix_credit_accounts_status',
                        'credit_accounts', ['status'])
        op.create_index('ix_credit_account_user_status',
                        'credit_accounts', ['user_id', 'status'])

    if 'credit_statements' not in tables:
        op.create_table(
            'credit_statements',
            sa.Column('statement_id', sa.CHAR(36), primary_key=True),
            sa.Column('credit_account_id', sa.CHAR(36),
                      sa.ForeignKey('credit_accounts.credit_account_id'),
                      nullable=False),
            sa.Column('user_id', sa.CHAR(36),
                      sa.ForeignKey('users.user_id'), nullable=False),
            sa.Column('statement_number', sa.String(24), nullable=False,
                      unique=True),

            sa.Column('period_start', sa.Date(), nullable=False),
            sa.Column('period_end', sa.Date(), nullable=False),
            sa.Column('statement_date', sa.Date(), nullable=False),
            sa.Column('due_date', sa.Date(), nullable=False),

            sa.Column('opening_balance', sa.Numeric(12, 2), nullable=False),
            sa.Column('total_purchases', sa.Numeric(12, 2), nullable=False,
                      server_default='0'),
            sa.Column('total_payments', sa.Numeric(12, 2), nullable=False,
                      server_default='0'),
            sa.Column('total_refunds', sa.Numeric(12, 2), nullable=False,
                      server_default='0'),
            sa.Column('total_fees', sa.Numeric(12, 2), nullable=False,
                      server_default='0'),
            sa.Column('closing_balance', sa.Numeric(12, 2), nullable=False),
            sa.Column('minimum_due', sa.Numeric(12, 2), nullable=False),
            sa.Column('minimum_due_percent', sa.Numeric(5, 2), nullable=False),

            sa.Column('amount_paid', sa.Numeric(12, 2), nullable=False,
                      server_default='0'),
            sa.Column('status', sa.String(20), nullable=False),
            sa.Column('fully_paid_at', sa.DateTime(), nullable=True),
            sa.Column('late_fee_charged_at', sa.DateTime(), nullable=True),

            sa.Column('created_on', sa.DateTime(), nullable=False),
            sa.Column('updated_on', sa.DateTime(), nullable=False),

            # One statement per account per cycle. This is what makes the
            # statement job idempotent rather than a check-then-write.
            sa.UniqueConstraint('credit_account_id', 'period_end',
                                name='uq_statement_period'),
        )
        op.create_index('ix_credit_statements_credit_account_id',
                        'credit_statements', ['credit_account_id'])
        op.create_index('ix_credit_statements_user_id',
                        'credit_statements', ['user_id'])
        op.create_index('ix_credit_statements_due_date',
                        'credit_statements', ['due_date'])
        op.create_index('ix_credit_statements_status',
                        'credit_statements', ['status'])
        op.create_index('ix_statement_account_period',
                        'credit_statements', ['credit_account_id', 'period_end'])

    if 'credit_transactions' not in tables:
        op.create_table(
            'credit_transactions',
            sa.Column('credit_transaction_id', sa.CHAR(36), primary_key=True),
            sa.Column('credit_account_id', sa.CHAR(36),
                      sa.ForeignKey('credit_accounts.credit_account_id'),
                      nullable=False),
            sa.Column('user_id', sa.CHAR(36),
                      sa.ForeignKey('users.user_id'), nullable=False),
            sa.Column('transaction_id', sa.String(36), nullable=True),

            sa.Column('transaction_type', sa.String(20), nullable=False),
            sa.Column('status', sa.String(20), nullable=False),

            sa.Column('amount', sa.Numeric(12, 2), nullable=False),
            sa.Column('balance_after', sa.Numeric(12, 2), nullable=True),

            sa.Column('merchant_name', sa.String(120), nullable=True),
            sa.Column('merchant_category', sa.String(20), nullable=True),
            sa.Column('description', sa.String(200), nullable=True),

            # The duplicate-charge defence. A constraint, not a check in code.
            sa.Column('idempotency_key', sa.String(64), nullable=False,
                      unique=True),

            sa.Column('statement_id', sa.String(36),
                      sa.ForeignKey('credit_statements.statement_id'),
                      nullable=True),
            sa.Column('reverses_credit_transaction_id', sa.String(36),
                      nullable=True),

            sa.Column('failure_code', sa.String(50), nullable=True),
            sa.Column('failure_reason', sa.String(500), nullable=True),
            sa.Column('is_test', sa.Boolean(), nullable=False,
                      server_default=sa.false()),
            sa.Column('settled_at', sa.DateTime(), nullable=True),

            sa.Column('created_on', sa.DateTime(), nullable=False),
            sa.Column('updated_on', sa.DateTime(), nullable=False),
        )
        op.create_index('ix_credit_transactions_credit_account_id',
                        'credit_transactions', ['credit_account_id'])
        op.create_index('ix_credit_transactions_user_id',
                        'credit_transactions', ['user_id'])
        op.create_index('ix_credit_transactions_transaction_id',
                        'credit_transactions', ['transaction_id'])
        op.create_index('ix_credit_transactions_transaction_type',
                        'credit_transactions', ['transaction_type'])
        op.create_index('ix_credit_transactions_status',
                        'credit_transactions', ['status'])
        op.create_index('ix_credit_transactions_idempotency_key',
                        'credit_transactions', ['idempotency_key'])
        op.create_index('ix_credit_transactions_reverses',
                        'credit_transactions',
                        ['reverses_credit_transaction_id'])
        op.create_index('ix_credit_txn_account_created',
                        'credit_transactions',
                        ['credit_account_id', 'created_on'])
        op.create_index('ix_credit_txn_statement',
                        'credit_transactions', ['statement_id'])


def downgrade():
    # Child first: credit_transactions references both accounts and statements.
    for table in ('credit_transactions', 'credit_statements',
                  'credit_accounts', 'credit_applications'):
        op.drop_table(table)
